# Generated by Django 4.0.4 on 2022-12-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ism Familya')),
                ('age', models.DateField(verbose_name="Tug'ligan yili")),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon raqam')),
                ('address', models.CharField(max_length=255, verbose_name='Yashash manzili')),
            ],
        ),
    ]
